
import React, { useState, useEffect, useRef } from 'react';
import { 
  Play, 
  Save, 
  Settings, 
  Sparkles, 
  Terminal, 
  ChevronDown,
  CheckCircle,
  AlertCircle,
  Trash2,
  Eye,
  EyeOff,
  RefreshCw,
  Database,
  Layers,
  Clock
} from 'lucide-react';
import { ServerlessFunction, FunctionStatus, Runtime, LogEntry, InvocationResult, Binding } from '../types';
import { generateFunctionCode, analyzeErrorLog } from '../services/geminiService';
import { PlatformService } from '../services/platform';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar } from 'recharts';

interface Props {
  func: ServerlessFunction;
  onSave: (updated: ServerlessFunction) => void;
}

const TABS = ['Code', 'Configuration', 'Bindings', 'Metrics', 'Test'];

export const FunctionEditor: React.FC<Props> = ({ func, onSave }) => {
  const [activeTab, setActiveTab] = useState('Code');
  const [code, setCode] = useState(func.code);
  const [isDeploying, setIsDeploying] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  
  // Test Result State
  const [testResult, setTestResult] = useState<InvocationResult | null>(null);
  const [isTesting, setIsTesting] = useState(false);
  
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [localFunc, setLocalFunc] = useState(func);
    const [rateLimit, setRateLimit] = useState<{ tokens: number; capacity: number } | null>(null);
    const [bindingOps, setBindingOps] = useState<LogEntry[]>([]);
    const [containerStatus, setContainerStatus] = useState<{ instanceId: string; status: string; busy?: boolean } | null>(null);
    const [testAuthHeader, setTestAuthHeader] = useState<string>('');
    const [logFilter, setLogFilter] = useState<'ALL' | 'INFO' | 'WARN' | 'ERROR' | 'DEBUG'>('ALL');
    const [logSearch, setLogSearch] = useState<string>('');
    const [functionMetrics, setFunctionMetrics] = useState<any[]>([]);
  
  // Config state
  const [showSecret, setShowSecret] = useState<Record<string, boolean>>({});

  useEffect(() => {
      setLocalFunc(func);
      setCode(func.code);
      fetchLogs();
      fetchRateLimit();
      fetchContainerStatus();
  }, [func.id]);

  const fetchLogs = async () => {
      const fetchedLogs = await PlatformService.getLogs(func.id);
      setLogs(fetchedLogs);
      setBindingOps(fetchedLogs.filter(l => l.message && (l.message.includes('Output binding') || l.message.includes('Output binding wrote') || l.message.includes('No binding injected'))));
      
      // Calculate metrics from logs
      const hourlyMetrics: Record<string, { invocations: number; errors: number; totalLatency: number; count: number }> = {};
      for (const log of fetchedLogs) {
        const hour = new Date(log.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
        if (!hourlyMetrics[hour]) {
          hourlyMetrics[hour] = { invocations: 0, errors: 0, totalLatency: 0, count: 0 };
        }
        if (log.level === 'REPORT') {
          hourlyMetrics[hour].invocations += 1;
          if (log.duration) {
            hourlyMetrics[hour].totalLatency += log.duration;
            hourlyMetrics[hour].count += 1;
          }
        } else if (log.level === 'ERROR') {
          hourlyMetrics[hour].errors += 1;
        }
      }
      
      const metricsData = Object.entries(hourlyMetrics).map(([time, data]) => ({
        time,
        invocations: data.invocations,
        errors: data.errors,
        latency: data.count > 0 ? Math.round(data.totalLatency / data.count) : 0
      }));
      setFunctionMetrics(metricsData);
  };

    const fetchRateLimit = async () => {
            try {
                // @ts-ignore
                const rl = await PlatformService.getRateLimitStatus(func.id);
                setRateLimit({ tokens: rl.tokens, capacity: rl.capacity });
            } catch (e) {
                setRateLimit(null);
            }
    };

  const handleGenerate = async () => {
    if (!aiPrompt) return;
    setIsGenerating(true);
    try {
      const generated = await generateFunctionCode(aiPrompt, func.runtime);
      setCode(prev => `// Generated by Nexus AI\n${generated}\n\n// Previous Code:\n${prev}`);
      setAiPrompt('');
    } catch (e) {
      console.error(e);
    } finally {
      setIsGenerating(false);
    }
  };

    const fetchContainerStatus = async () => {
            try {
                // @ts-ignore
                const st = await PlatformService.getContainerStatus(func.id);
                setContainerStatus(st);
            } catch (e) {
                setContainerStatus(null);
            }
    };

  const handleSave = async () => {
    setIsDeploying(true);
    try {
        const updated = await PlatformService.deployFunction(func.id, code);
        onSave(updated);
        setLocalFunc(updated);
        fetchLogs();
    } catch (e) {
        console.error("Deployment failed", e);
    } finally {
        setIsDeploying(false);
    }
  };

  const handleUpdateConfig = async (updates: Partial<ServerlessFunction>) => {
      const updated = await PlatformService.updateConfiguration(func.id, updates);
      setLocalFunc(updated);
      onSave(updated);
  };

  const runTest = async () => {
    setIsTesting(true);
    setTestResult(null);
    try {
        // Execute real function code in the worker
        const response = await PlatformService.invokeFunction(func.id, JSON.stringify({ test: true, timestamp: Date.now() }), testAuthHeader || undefined);
        // Update rate limit after invocation
        fetchRateLimit();
        setTestResult(response);
        fetchLogs();
    } catch (e) {
        console.error(e);
        // Create a local error log if execution crashes completely
        setTestResult({
            result: { statusCode: 500, body: { error: "Execution Crash" } },
            log: { 
                id: Date.now().toString(), 
                timestamp: new Date().toISOString(), 
                level: 'ERROR', 
                message: String(e), 
                requestId: 'err' 
            },
            trace: { id: 'err', requestId: 'err', spans: [] }
        });
    } finally {
        setIsTesting(false);
    }
  }

  return (
    <div className="flex flex-col h-[calc(100vh-4rem)] bg-slate-950">
      {/* Editor Header */}
      <div className="h-14 border-b border-slate-800 bg-slate-900/50 flex items-center justify-between px-6 backdrop-blur-md z-10">
        <div className="flex items-center space-x-4">
          <h2 className="text-lg font-semibold text-white">{localFunc.name}</h2>
          <span className="px-2 py-0.5 rounded text-xs font-medium bg-slate-800 text-slate-400 border border-slate-700">
            {localFunc.runtime}
          </span>
          <span className="px-2 py-0.5 rounded text-xs font-medium bg-slate-800 text-primary-400 border border-slate-700">
            {localFunc.version}
          </span>
          <span className={`px-2 py-0.5 rounded text-xs font-medium flex items-center gap-1 ${
            localFunc.status === FunctionStatus.ACTIVE ? 'bg-emerald-500/10 text-emerald-500 border border-emerald-500/20' : 
            localFunc.status === FunctionStatus.DEPLOYING ? 'bg-blue-500/10 text-blue-500 border border-blue-500/20' :
            'bg-amber-500/10 text-amber-500 border border-amber-500/20'
          }`}>
            {localFunc.status === FunctionStatus.ACTIVE ? <CheckCircle size={10} /> : <AlertCircle size={10} />}
            {isDeploying ? 'Deploying...' : localFunc.status}
          </span>
        </div>
                <div className="flex items-center space-x-2">
                    {rateLimit && (
                        <div className={`px-2 py-0.5 rounded text-xs font-medium border ${rateLimit.tokens <= 0 ? 'bg-rose-500/10 text-rose-400 border-rose-500/20' : 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20'}`}>
                            Rate: {rateLimit.tokens}/{rateLimit.capacity}
                        </div>
                    )}
                    <button 
                        onClick={runTest}
                        disabled={isTesting || (rateLimit && rateLimit.tokens <= 0)}
            className={`flex items-center px-3 py-1.5 text-sm font-medium text-slate-300 hover:text-white hover:bg-slate-800 rounded-md transition-colors ${isTesting ? 'opacity-50' : ''}`}
          >
            <Play size={16} className={`mr-2 text-emerald-500 ${isTesting ? 'animate-pulse' : ''}`} />
                        {isTesting ? 'Running...' : rateLimit && rateLimit.tokens <= 0 ? 'Rate Limited' : 'Test'}
          </button>
          <button 
            onClick={handleSave}
            disabled={isDeploying}
            className={`flex items-center px-3 py-1.5 text-sm font-medium text-white bg-primary-600 hover:bg-primary-500 rounded-md transition-colors shadow-lg shadow-primary-900/20 ${isDeploying ? 'opacity-50 cursor-not-allowed' : ''}`}
          >
            <Save size={16} className="mr-2" />
            {isDeploying ? 'Deploying...' : 'Deploy'}
          </button>
        </div>
      </div>

      {/* Main Area */}
      <div className="flex flex-1 overflow-hidden">
        {/* Tabs & Content */}
        <div className="flex-1 flex flex-col border-r border-slate-800">
          <div className="flex border-b border-slate-800 bg-slate-900/30">
            {TABS.map(tab => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`px-6 py-3 text-sm font-medium border-b-2 transition-colors ${
                  activeTab === tab 
                    ? 'border-primary-500 text-primary-400 bg-primary-500/5' 
                    : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/50'
                }`}
              >
                {tab}
              </button>
            ))}
          </div>

          <div className="flex-1 relative bg-[#0d1117] overflow-auto">
            {activeTab === 'Code' && (
              <div className="h-full flex flex-col">
                 {/* AI Bar */}
                 <div className="p-2 bg-slate-900 border-b border-slate-800 flex gap-2">
                    <div className="relative flex-1">
                      <Sparkles className="absolute left-3 top-1/2 -translate-y-1/2 text-purple-400" size={16} />
                      <input 
                        type="text" 
                        value={aiPrompt}
                        onChange={(e) => setAiPrompt(e.target.value)}
                        placeholder="Ask Nexus AI to generate code (e.g., 'Process S3 event and resize image')..." 
                        className="w-full bg-slate-950 border border-slate-700 rounded pl-10 pr-4 py-1.5 text-sm text-slate-200 focus:outline-none focus:border-purple-500 focus:ring-1 focus:ring-purple-500 placeholder-slate-600"
                        onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
                      />
                    </div>
                    <button 
                      onClick={handleGenerate}
                      disabled={isGenerating || !aiPrompt}
                      className="bg-purple-600 hover:bg-purple-500 text-white px-3 py-1.5 rounded text-xs font-bold uppercase tracking-wider disabled:opacity-50"
                    >
                      {isGenerating ? 'Generating...' : 'Generate'}
                    </button>
                 </div>

                <textarea
                  value={code}
                  onChange={(e) => setCode(e.target.value)}
                  className="flex-1 w-full bg-[#0d1117] text-slate-300 p-4 font-mono text-sm resize-none focus:outline-none leading-relaxed"
                  spellCheck="false"
                />
              </div>
            )}

            {activeTab === 'Configuration' && (
              <div className="p-8 max-w-3xl">
                <h3 className="text-white font-medium mb-4">HTTP Triggers</h3>
                <div className="space-y-3 mb-8 bg-slate-900/50 p-4 rounded-lg border border-slate-800">
                    {localFunc.triggers.filter(t => t.type === 'HTTP').length === 0 ? (
                        <div className="text-slate-500 text-sm italic py-4">No HTTP triggers configured. Add one below.</div>
                    ) : (
                        localFunc.triggers.filter(t => t.type === 'HTTP').map((trigger, idx) => (
                            <div key={trigger.id} className="flex gap-2 items-center bg-slate-800 p-3 rounded border border-slate-700">
                                <select 
                                    value={trigger.config.method || 'POST'} 
                                    onChange={(e) => {
                                        const updated = [...localFunc.triggers];
                                        const triggerIdx = updated.findIndex(t => t.id === trigger.id);
                                        if (triggerIdx !== -1) {
                                            updated[triggerIdx].config.method = e.target.value;
                                            setLocalFunc({...localFunc, triggers: updated});
                                        }
                                    }}
                                    className="bg-slate-700 border border-slate-600 rounded px-2 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-primary-500"
                                >
                                    <option>GET</option>
                                    <option>POST</option>
                                    <option>PUT</option>
                                    <option>DELETE</option>
                                    <option>PATCH</option>
                                </select>
                                <input 
                                    type="text" 
                                    value={trigger.config.path || '/'} 
                                    onChange={(e) => {
                                        const updated = [...localFunc.triggers];
                                        const triggerIdx = updated.findIndex(t => t.id === trigger.id);
                                        if (triggerIdx !== -1) {
                                            updated[triggerIdx].config.path = e.target.value;
                                            setLocalFunc({...localFunc, triggers: updated});
                                        }
                                    }}
                                    placeholder="/api/path" 
                                    className="flex-1 bg-slate-700 border border-slate-600 rounded px-2 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-primary-500" 
                                />
                                <button 
                                    onClick={() => {
                                        const updated = localFunc.triggers.filter(t => t.id !== trigger.id);
                                        setLocalFunc({...localFunc, triggers: updated});
                                    }}
                                    className="text-slate-500 hover:text-rose-500"
                                >
                                    <Trash2 size={16} />
                                </button>
                            </div>
                        ))
                    )}
                    <button 
                        onClick={() => {
                            const newTrigger = {
                                id: `t-${Date.now()}`,
                                type: 'HTTP' as const,
                                config: { method: 'POST', path: '/api/new' }
                            };
                            setLocalFunc({...localFunc, triggers: [...localFunc.triggers, newTrigger]});
                        }}
                        className="w-full py-2 bg-slate-700 hover:bg-slate-600 text-slate-300 rounded text-sm transition-colors border border-slate-600"
                    >
                        + Add HTTP Trigger
                    </button>
                </div>

                <h3 className="text-white font-medium mb-4">CRON Triggers</h3>
                <div className="space-y-3 mb-8 bg-slate-900/50 p-4 rounded-lg border border-slate-800">
                    {localFunc.triggers.filter(t => t.type === 'CRON').length === 0 ? (
                        <div className="text-slate-500 text-sm italic py-4">No CRON triggers configured. Add one below.</div>
                    ) : (
                        localFunc.triggers.filter(t => t.type === 'CRON').map((trigger) => (
                            <div key={trigger.id} className="flex gap-2 items-center bg-slate-800 p-3 rounded border border-slate-700">
                                <span className="text-xs text-slate-400 w-12">Schedule:</span>
                                <input 
                                    type="text" 
                                    value={trigger.config.schedule || ''} 
                                    onChange={(e) => {
                                        const updated = [...localFunc.triggers];
                                        const triggerIdx = updated.findIndex(t => t.id === trigger.id);
                                        if (triggerIdx !== -1) {
                                            updated[triggerIdx].config.schedule = e.target.value;
                                            setLocalFunc({...localFunc, triggers: updated});
                                        }
                                    }}
                                    placeholder="0 0 * * * (Unix cron format)" 
                                    className="flex-1 bg-slate-700 border border-slate-600 rounded px-2 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-primary-500 font-mono" 
                                />
                                <button 
                                    onClick={() => {
                                        const updated = localFunc.triggers.filter(t => t.id !== trigger.id);
                                        setLocalFunc({...localFunc, triggers: updated});
                                    }}
                                    className="text-slate-500 hover:text-rose-500"
                                >
                                    <Trash2 size={16} />
                                </button>
                            </div>
                        ))
                    )}
                    <button 
                        onClick={() => {
                            const newTrigger = {
                                id: `t-${Date.now()}`,
                                type: 'CRON' as const,
                                config: { schedule: '0 0 * * *' }
                            };
                            setLocalFunc({...localFunc, triggers: [...localFunc.triggers, newTrigger]});
                        }}
                        className="w-full py-2 bg-slate-700 hover:bg-slate-600 text-slate-300 rounded text-sm transition-colors border border-slate-600"
                    >
                        + Add CRON Trigger
                    </button>
                </div>

                <h3 className="text-white font-medium mb-4">Environment Variables</h3>
                <div className="space-y-3 mb-8 bg-slate-900/50 p-4 rounded-lg border border-slate-800">
                    {localFunc.envVars.length === 0 ? (
                        <div className="text-slate-500 text-sm italic py-4">No environment variables configured.</div>
                    ) : (
                        localFunc.envVars.map((env, idx) => (
                            <div key={idx} className="flex gap-2 items-center bg-slate-800 p-3 rounded border border-slate-700">
                                <input 
                                    type="text" 
                                    value={env.key} 
                                    onChange={(e) => {
                                        const updated = [...localFunc.envVars];
                                        updated[idx].key = e.target.value;
                                        setLocalFunc({...localFunc, envVars: updated});
                                    }}
                                    placeholder="KEY" 
                                    className="bg-slate-700 border border-slate-600 rounded px-2 py-1.5 text-xs text-slate-300 w-1/4 focus:outline-none focus:border-primary-500" 
                                />
                                <div className="flex-1 relative">
                                    <input 
                                        type={env.isSecret && !showSecret[env.key] ? "password" : "text"} 
                                        value={env.value} 
                                        onChange={(e) => {
                                            const updated = [...localFunc.envVars];
                                            updated[idx].value = e.target.value;
                                            setLocalFunc({...localFunc, envVars: updated});
                                        }}
                                        placeholder="value" 
                                        className="w-full bg-slate-700 border border-slate-600 rounded px-2 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-primary-500 pr-8" 
                                    />
                                    {env.isSecret && (
                                        <button 
                                            className="absolute right-2 top-1/2 -translate-y-1/2 text-slate-500 hover:text-white"
                                            onClick={() => setShowSecret(prev => ({...prev, [env.key]: !prev[env.key]}))}
                                        >
                                            {showSecret[env.key] ? <EyeOff size={14}/> : <Eye size={14}/>}
                                        </button>
                                    )}
                                </div>
                                <button 
                                    onClick={() => {
                                        const updated = localFunc.envVars.filter((_, i) => i !== idx);
                                        setLocalFunc({...localFunc, envVars: updated});
                                    }}
                                    className="text-slate-500 hover:text-rose-500"
                                >
                                    <Trash2 size={16} />
                                </button>
                            </div>
                        ))
                    )}
                    <button 
                        onClick={() => {
                            const newEnv = {
                                key: `NEW_VAR_${localFunc.envVars.length + 1}`,
                                value: '',
                                isSecret: false
                            };
                            setLocalFunc({...localFunc, envVars: [...localFunc.envVars, newEnv]});
                        }}
                        className="w-full py-2 bg-slate-700 hover:bg-slate-600 text-slate-300 rounded text-sm transition-colors border border-slate-600"
                    >
                        + Add Environment Variable
                    </button>
                </div>

                <h3 className="text-white font-medium mb-4">Resources</h3>
                <div className="space-y-6 bg-slate-900/50 p-6 rounded-lg border border-slate-800">
                    <div>
                        <div className="flex justify-between text-sm text-slate-400 mb-2">
                            <span>Memory Allocation</span>
                            <span className="text-white">{localFunc.memory} MB</span>
                        </div>
                        <input 
                            type="range" 
                            min="128" 
                            max="3072" 
                            step="128"
                            value={localFunc.memory}
                            onChange={(e) => setLocalFunc({...localFunc, memory: parseInt(e.target.value)})}
                            className="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-primary-500"
                        />
                    </div>
                    
                    <div>
                        <div className="flex justify-between text-sm text-slate-400 mb-2">
                            <span>Timeout</span>
                            <span className="text-white">{localFunc.timeout} sec</span>
                        </div>
                        <input 
                            type="range" 
                            min="1" 
                            max="900" 
                            value={localFunc.timeout}
                            onChange={(e) => setLocalFunc({...localFunc, timeout: parseInt(e.target.value)})}
                            className="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-primary-500"
                        />
                    </div>
                </div>
                <button 
                    onClick={() => handleUpdateConfig({ memory: localFunc.memory, timeout: localFunc.timeout, triggers: localFunc.triggers, envVars: localFunc.envVars })}
                    className="mt-6 bg-primary-600 text-white px-4 py-2 rounded text-sm"
                >
                    Save Configuration
                </button>
              </div>
            )}

            {activeTab === 'Bindings' && (
                <div className="p-8 max-w-3xl">
                    <div className="flex justify-between items-center mb-6">
                        <div>
                            <h3 className="text-white font-medium">Infrastructure Bindings</h3>
                            <p className="text-sm text-slate-400">Connect external services (databases, storage, queues) to your functions.</p>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 gap-4 mb-8">
                        {localFunc.bindings.length === 0 && (
                            <div className="p-8 border-2 border-dashed border-slate-800 rounded-lg text-center text-slate-500">
                                No bindings configured. Add one below.
                            </div>
                        )}
                        {localFunc.bindings.map((binding, idx) => (
                            <div key={binding.id} className="bg-slate-900 border border-slate-800 rounded-lg p-4">
                                <div className="flex items-start gap-4 mb-3">
                                    <div className="flex-1">
                                        <input 
                                            type="text"
                                            value={binding.name}
                                            onChange={(e) => {
                                                const updated = [...localFunc.bindings];
                                                updated[idx].name = e.target.value;
                                                setLocalFunc({...localFunc, bindings: updated});
                                            }}
                                            placeholder="Binding name"
                                            className="bg-slate-800 border border-slate-700 rounded px-2 py-1.5 text-sm text-slate-300 w-full focus:outline-none focus:border-primary-500 mb-2"
                                        />
                                        <div className="flex gap-2 mb-2">
                                            <select 
                                                value={binding.type}
                                                onChange={(e) => {
                                                    const updated = [...localFunc.bindings];
                                                    updated[idx].type = e.target.value as any;
                                                    setLocalFunc({...localFunc, bindings: updated});
                                                }}
                                                className="bg-slate-800 border border-slate-700 rounded px-2 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-primary-500"
                                            >
                                                <option>postgres</option>
                                                <option>redis</option>
                                                <option>s3</option>
                                                <option>sqs</option>
                                                <option>dynamodb</option>
                                            </select>
                                            <select 
                                                value={binding.direction}
                                                onChange={(e) => {
                                                    const updated = [...localFunc.bindings];
                                                    updated[idx].direction = e.target.value as any;
                                                    setLocalFunc({...localFunc, bindings: updated});
                                                }}
                                                className="bg-slate-800 border border-slate-700 rounded px-2 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-primary-500"
                                            >
                                                <option>input</option>
                                                <option>output</option>
                                                <option>bidirectional</option>
                                            </select>
                                        </div>
                                        <textarea 
                                            value={JSON.stringify(binding.config, null, 2)}
                                            onChange={(e) => {
                                                try {
                                                    const updated = [...localFunc.bindings];
                                                    updated[idx].config = JSON.parse(e.target.value);
                                                    setLocalFunc({...localFunc, bindings: updated});
                                                } catch (err) {
                                                    // Invalid JSON, ignore
                                                }
                                            }}
                                            placeholder="Connection config (JSON)"
                                            className="w-full bg-slate-800 border border-slate-700 rounded px-2 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-primary-500 font-mono h-24"
                                        />
                                    </div>
                                    <button 
                                        onClick={() => {
                                            const updated = localFunc.bindings.filter((_, i) => i !== idx);
                                            setLocalFunc({...localFunc, bindings: updated});
                                        }}
                                        className="text-slate-500 hover:text-rose-500 mt-1"
                                    >
                                        <Trash2 size={18} />
                                    </button>
                                </div>
                            </div>
                        ))}
                    </div>

                    <button 
                        onClick={() => {
                            const newBinding = {
                                id: `b-${Date.now()}`,
                                name: 'new-binding',
                                type: 'postgres' as const,
                                direction: 'input' as const,
                                config: { host: 'localhost', port: 5432 }
                            };
                            setLocalFunc({...localFunc, bindings: [...localFunc.bindings, newBinding]});
                        }}
                        className="w-full py-3 bg-primary-600 hover:bg-primary-500 text-white rounded text-sm font-medium transition-colors"
                    >
                        + Add Binding
                    </button>

                    <button 
                        onClick={() => handleUpdateConfig({ bindings: localFunc.bindings })}
                        className="w-full mt-3 py-2 bg-slate-700 hover:bg-slate-600 text-slate-300 rounded text-sm transition-colors"
                    >
                        Save Bindings
                    </button>
                </div>
            )}

            {activeTab === 'Metrics' && (
                <div className="p-8 h-full flex flex-col space-y-6">
                    <div>
                        <h3 className="text-white font-medium mb-2">Invocation Volume</h3>
                        <div className="bg-slate-950 border border-slate-800 rounded p-4 h-64">
                            {functionMetrics.length > 0 ? (
                                <ResponsiveContainer width="100%" height="100%">
                                    <AreaChart data={functionMetrics}>
                                        <defs>
                                            <linearGradient id="colorInv" x1="0" y1="0" x2="0" y2="1">
                                                <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.3}/>
                                                <stop offset="95%" stopColor="#3b82f6" stopOpacity={0}/>
                                            </linearGradient>
                                        </defs>
                                        <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                                        <XAxis dataKey="time" stroke="#94a3b8" fontSize={10} tickLine={false} axisLine={false} />
                                        <YAxis stroke="#94a3b8" fontSize={10} tickLine={false} axisLine={false} />
                                        <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#1e293b', color: '#f8fafc' }} />
                                        <Area type="monotone" dataKey="invocations" stroke="#3b82f6" strokeWidth={2} fillOpacity={1} fill="url(#colorInv)" />
                                    </AreaChart>
                                </ResponsiveContainer>
                            ) : (
                                <div className="flex items-center justify-center h-full text-slate-500 text-sm">No invocation data yet</div>
                            )}
                        </div>
                    </div>

                    <div className="grid grid-cols-2 gap-6">
                        <div>
                            <h3 className="text-white font-medium mb-2">Error Rate</h3>
                            <div className="bg-slate-950 border border-slate-800 rounded p-4 h-48">
                                {functionMetrics.length > 0 ? (
                                    <ResponsiveContainer width="100%" height="100%">
                                        <BarChart data={functionMetrics}>
                                            <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                                            <XAxis dataKey="time" stroke="#94a3b8" fontSize={10} tickLine={false} axisLine={false} />
                                            <YAxis stroke="#94a3b8" fontSize={10} tickLine={false} axisLine={false} />
                                            <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#1e293b', color: '#f8fafc' }} />
                                            <Bar dataKey="errors" fill="#ef4444" radius={[4, 4, 0, 0]} />
                                        </BarChart>
                                    </ResponsiveContainer>
                                ) : (
                                    <div className="flex items-center justify-center h-full text-slate-500 text-sm">No error data yet</div>
                                )}
                            </div>
                        </div>

                        <div>
                            <h3 className="text-white font-medium mb-2">Avg Latency (ms)</h3>
                            <div className="bg-slate-950 border border-slate-800 rounded p-4 h-48">
                                {functionMetrics.length > 0 ? (
                                    <ResponsiveContainer width="100%" height="100%">
                                        <AreaChart data={functionMetrics}>
                                            <defs>
                                                <linearGradient id="colorLat" x1="0" y1="0" x2="0" y2="1">
                                                    <stop offset="5%" stopColor="#10b981" stopOpacity={0.3}/>
                                                    <stop offset="95%" stopColor="#10b981" stopOpacity={0}/>
                                                </linearGradient>
                                            </defs>
                                            <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                                            <XAxis dataKey="time" stroke="#94a3b8" fontSize={10} tickLine={false} axisLine={false} />
                                            <YAxis stroke="#94a3b8" fontSize={10} tickLine={false} axisLine={false} />
                                            <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#1e293b', color: '#f8fafc' }} />
                                            <Area type="monotone" dataKey="latency" stroke="#10b981" strokeWidth={2} fillOpacity={1} fill="url(#colorLat)" />
                                        </AreaChart>
                                    </ResponsiveContainer>
                                ) : (
                                    <div className="flex items-center justify-center h-full text-slate-500 text-sm">No latency data yet</div>
                                )}
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {activeTab === 'Test' && (
                <div className="p-4 h-full flex flex-col">
                    <div className="mb-3">
                        <label className="block text-xs font-medium text-slate-500 uppercase mb-2">Authorization Header (Optional)</label>
                        <div className="flex gap-2 mb-2">
                            <select 
                                className="flex-1 bg-slate-800 border border-slate-700 rounded px-3 py-2 text-sm text-slate-300 focus:outline-none focus:border-primary-500"
                                defaultValue="api-key"
                            >
                                <option value="api-key">API Key: sk-test-abc123</option>
                                <option value="api-key-2">API Key: sk-test-xyz789</option>
                                <option value="bearer">Bearer (Mock JWT)</option>
                            </select>
                            <button 
                                onClick={() => setTestAuthHeader('')}
                                className="px-3 py-2 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded text-sm text-slate-400 transition-colors"
                            >
                                Clear
                            </button>
                        </div>
                        <input 
                            type="text"
                            placeholder="e.g., apikey sk-test-abc123 or bearer eyJhbGc..."
                            className="w-full bg-slate-800 border border-slate-700 rounded px-3 py-2 text-sm font-mono text-slate-300 focus:outline-none focus:border-primary-500 transition-colors"
                            value={testAuthHeader}
                            onChange={(e) => setTestAuthHeader(e.target.value)}
                        />
                    </div>
                    <div className="mb-4">
                        <label className="block text-xs font-medium text-slate-500 uppercase mb-2">Test Event JSON</label>
                        <textarea 
                            className="w-full h-32 bg-slate-800 border border-slate-700 rounded p-3 text-sm font-mono text-slate-300 focus:outline-none focus:border-primary-500 transition-colors"
                            defaultValue={JSON.stringify({ key1: "value1", key2: "value2" }, null, 2)}
                        />
                    </div>
                    <div className="flex-1 flex flex-col gap-4 overflow-hidden">
                        <div className="flex-1 bg-slate-950 border border-slate-800 rounded flex flex-col overflow-hidden">
                            <div className="bg-slate-900 p-2 border-b border-slate-800 text-xs font-medium text-slate-400 flex items-center gap-2">
                                <Terminal size={12} /> Execution Output
                            </div>
                            <div className="flex-1 p-4 overflow-auto font-mono text-sm">
                                {testResult ? (
                                    <>
                                        <div className="text-slate-500 mb-2">// Status: {testResult.result.statusCode}</div>
                                                                                <pre className="text-emerald-400">{JSON.stringify(testResult.result.body, null, 2)}</pre>
                                                                                <div className="text-slate-400 mt-2">
                                                                                    <div className="text-xs"><strong>Event:</strong></div>
                                                                                    <pre className="text-xs text-slate-500">{JSON.stringify(testResult.event ?? {}, null, 2)}</pre>
                                                                                    <div className="text-xs mt-2"><strong>Context:</strong></div>
                                                                                    <pre className="text-xs text-slate-500">{JSON.stringify(testResult.context ?? {}, null, 2)}</pre>
                                                                                </div>
                                    </>
                                ) : (
                                    <span className="text-slate-600 italic">Run a test to see real execution results...</span>
                                )}
                            </div>
                        </div>

                    {bindingOps.length > 0 && (
                        <div className="mt-2 p-3 bg-slate-900 border border-slate-800 rounded text-xs text-slate-300">
                            <div className="mb-2 text-slate-400 font-medium">Binding Operations</div>
                            <div className="space-y-2 font-mono text-xs">
                                {bindingOps.map(b => (
                                    <div key={b.id} className={`pl-2 py-1 border-l-2 ${b.level === 'ERROR' ? 'border-rose-500 text-rose-400' : 'border-emerald-500 text-slate-400'}`}>
                                        <div className="flex justify-between text-slate-500 mb-0.5"><span>{new Date(b.timestamp).toLocaleTimeString()}</span></div>
                                        <div className="break-words">{b.message}</div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                        {testResult && (
                            <div className="h-1/2 bg-slate-950 border border-slate-800 rounded flex flex-col overflow-hidden">
                                <div className="bg-slate-900 p-2 border-b border-slate-800 text-xs font-medium text-slate-400 flex items-center gap-2">
                                    <Layers size={12} /> Distributed Trace
                                </div>
                                <div className="flex-1 p-4 overflow-auto">
                                    <div className="space-y-2">
                                        {testResult.trace.spans.map((span, i) => (
                                            <div key={span.id} className="flex items-center gap-2 text-xs font-mono group">
                                                <div className="w-24 text-right text-slate-500">
                                                    {span.duration}ms
                                                </div>
                                                <div className="flex-1 relative h-6">
                                                    <div 
                                                        className={`absolute h-4 top-1 rounded ${
                                                            span.service === 'api-gateway' ? 'bg-purple-500/30 border border-purple-500/50' :
                                                            span.service === 'worker-host' ? 'bg-blue-500/30 border border-blue-500/50' :
                                                            span.service === 'scheduler' ? 'bg-amber-500/30 border border-amber-500/50' :
                                                            'bg-emerald-500/30 border border-emerald-500/50'
                                                        }`}
                                                        style={{ 
                                                            left: `${(span.startTime - testResult.trace.spans[0].startTime) / 2}px`, 
                                                            width: `${Math.max(2, span.duration)}px` 
                                                        }}
                                                    ></div>
                                                    <span className="absolute left-0 -top-1 ml-1 text-[10px] text-slate-400 group-hover:text-white z-10">
                                                        {span.service}::{span.name}
                                                    </span>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            )}
          </div>
        </div>

        {/* Logs / Observability Sidebar */}
        <div className="w-80 bg-slate-900 border-l border-slate-800 flex flex-col">
           <div className="p-4 border-b border-slate-800 flex justify-between items-center">
              <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                <Settings size={14} /> Function Info
              </h3>
              <button onClick={fetchLogs} className="text-slate-500 hover:text-white p-1" title="Refresh Logs">
                  <RefreshCw size={14} />
              </button>
           </div>
           <div className="p-4 flex-1 overflow-y-auto">
               <div className="mb-6">
                   <label className="text-xs text-slate-500 uppercase font-bold block mb-2">Triggers</label>
                   {localFunc.triggers.map(t => (
                        <div key={t.id} className="bg-slate-800/50 rounded p-3 border border-slate-700 mb-2">
                            <div className="flex items-center justify-between mb-1">
                                <span className="text-sm text-white font-medium">{t.type}</span>
                                <span className="text-xs bg-emerald-500/20 text-emerald-400 px-1.5 py-0.5 rounded">{t.config.method || 'EVENT'}</span>
                            </div>
                            <div className="text-xs text-slate-400 truncate font-mono">
                                {t.config.path || t.config.schedule || 'queue-name'}
                            </div>
                        </div>
                   ))}
               </div>
               
                            <div className="mb-6">
                                     <label className="text-xs text-slate-500 uppercase font-bold block mb-2">Container</label>
                                     {containerStatus ? (
                                         <div className="bg-slate-800/50 rounded p-3 border border-slate-700 mb-2 text-sm">
                                             <div className="flex items-center justify-between"><span className="text-slate-300">Instance</span><span className="text-slate-500 font-mono">{containerStatus.instanceId}</span></div>
                                             <div className="mt-1 text-slate-400">Status: {containerStatus.status} {containerStatus.busy ? '(busy)' : ''}</div>
                                         </div>
                                     ) : (
                                         <div className="text-slate-600 italic">No active container</div>
                                     )}
                            </div>

               <div>
                   <label className="text-xs text-slate-500 uppercase font-bold block mb-2">Live Logs</label>
                   <div className="mb-3 space-y-2">
                       <input 
                           type="text"
                           placeholder="Search logs..."
                           value={logSearch}
                           onChange={(e) => setLogSearch(e.target.value)}
                           className="w-full bg-slate-800 border border-slate-700 rounded px-2 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-primary-500"
                       />
                       <select 
                           value={logFilter}
                           onChange={(e) => setLogFilter(e.target.value as any)}
                           className="w-full bg-slate-800 border border-slate-700 rounded px-2 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-primary-500"
                       >
                           <option value="ALL">All Levels</option>
                           <option value="INFO">INFO</option>
                           <option value="WARN">WARN</option>
                           <option value="ERROR">ERROR</option>
                           <option value="DEBUG">DEBUG</option>
                       </select>
                   </div>
                   <div className="space-y-2 font-mono text-xs max-h-64 overflow-y-auto">
                       {(() => {
                           const filtered = logs.filter(log => {
                               const levelMatch = logFilter === 'ALL' || log.level === logFilter;
                               const searchMatch = logSearch === '' || log.message.toLowerCase().includes(logSearch.toLowerCase());
                               return levelMatch && searchMatch;
                           });
                           
                           if (filtered.length === 0) {
                               return <div className="text-slate-600 italic">No logs matching filters.</div>;
                           }
                           
                           return filtered.map((log) => (
                               <div key={log.id} className={`pl-2 py-1 border-l-2 ${
                                   log.level === 'ERROR' ? 'border-rose-500 text-rose-400' : 
                                   log.level === 'WARN' ? 'border-amber-500 text-amber-400' : 
                                   log.level === 'DEBUG' ? 'border-slate-600 text-slate-500' :
                                   'border-emerald-500 text-slate-400'
                               }`}>
                                   <div className="flex justify-between text-slate-600 mb-0.5">
                                       <span>{new Date(log.timestamp).toLocaleTimeString()}</span>
                                       {log.coldStart && <span className="text-blue-400 flex items-center gap-0.5"><Clock size={10}/> Cold</span>}
                                    </div>
                                   <div className="break-words leading-snug">
                                       {log.message}
                                   </div>
                               </div>
                           ));
                       })()}
                   </div>
               </div>
           </div>
        </div>
      </div>
    </div>
  );
};
